export default {
    images: [
        {
            id: '1',
            source: require('../assets/Image1.png'), 
            thumbnail: require('../assets/Image1Thumbnail.png'),
            width: 1125,
            height: 2031,
            iconFromLeft: 947,
            iconFromTop: 1745,
            iconWidth: 10,
            iconHeight: 14.462
        },
        {
            id: '2',
            source: require('../assets/Image2.png'),
            thumbnail: require('../assets/Image2Thumbnail.png'),
            width: 1914.328,
            height: 3456,
            iconFromLeft: 76.447,
            iconFromTop: 1274.172,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '3',
            source: require('../assets/Image3.png'), 
            thumbnail: require('../assets/Image3Thumbnail.png'),
            width: 1862.814,
            height: 3363,
            iconFromLeft: 516.709,
            iconFromTop: 91.849,
            iconWidth: 82.207,
            iconHeight: 119.425
        },
        {
            id: '4',
            source: require('../assets/Image4.png'), 
            thumbnail: require('../assets/Image4Thumbnail.png'),
            width: 1862.814,
            height: 3363,
            iconFromLeft: 1231.907,
            iconFromTop: 1136.762,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '5',
            source: require('../assets/Image5.png'), 
            thumbnail: require('../assets/Image5Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1054.166,
            iconFromTop: 938.975,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '6',
            source: require('../assets/Image6.png'), 
            thumbnail: require('../assets/Image6Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1381.767,
            iconFromTop: 1460.694,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '7',
            source: require('../assets/Image7.png'), 
            thumbnail: require('../assets/Image7Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 946.692,
            iconFromTop: 1961.957,
            iconWidth: 18,
            iconHeight: 26.032 
        },
        {
            id: '8',
            source: require('../assets/Image8.png'), 
            thumbnail: require('../assets/Image8Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 106.703,
            iconFromTop: 701.035,
            iconWidth: 18,
            iconHeight: 26.032 
        },
        {
            id: '9',
            source: require('../assets/Image9.png'), 
            thumbnail: require('../assets/Image9Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 258.332,
            iconFromTop: 2126.488,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '10',
            source: require('../assets/Image10.png'), 
            thumbnail: require('../assets/Image10Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1204.21,
            iconFromTop: 2695.804,
            iconWidth: 18,
            iconHeight: 26.032 
        },
        {
            id: '11',
            source: require('../assets/Image11.png'), 
            thumbnail: require('../assets/Image11Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1312.723,
            iconFromTop: 2270.974,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '12',
            source: require('../assets/Image12.png'), 
            thumbnail: require('../assets/Image12Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1476.477,
            iconFromTop: 490.235,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '13',
            source: require('../assets/Image13.png'), 
            thumbnail: require('../assets/Image13Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 917.285,
            iconFromTop: 360.782,
            iconWidth: 15.048,
            iconHeight: 21.807 
        },
        {
            id: '14',
            source: require('../assets/Image14.png'), 
            thumbnail: require('../assets/Image14Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 169.055,
            iconFromTop: 1182.714,
            iconWidth: 24.009,
            iconHeight: 35.407
        },
        {
            id: '15',
            source: require('../assets/Image15.png'), 
            thumbnail: require('../assets/Image15Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 38.816,
            iconFromTop: 1053.009,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '16',
            source: require('../assets/Image16.png'), 
            thumbnail: require('../assets/Image16Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 665.184,
            iconFromTop: 2679.898,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '17',
            source: require('../assets/Image17.png'), 
            thumbnail: require('../assets/Image17Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 755.418,
            iconFromTop: 1605.426,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '18',
            source: require('../assets/Image18.png'), 
            thumbnail: require('../assets/Image18Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 755.418,
            iconFromTop: 1605.426,
            iconWidth: 15,
            iconHeight: 21.693
        },
        {
            id: '19',
            source: require('../assets/Image19.png'), 
            thumbnail: require('../assets/Image19Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1293.863,
            iconFromTop: 1345.658,
            iconWidth: 20,
            iconHeight: 28.924 
        },
        {
            id: '20',
            source: require('../assets/Image20.png'), 
            thumbnail: require('../assets/Image20Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 756.636,
            iconFromTop: 1741.552,
            iconWidth: 16,
            iconHeight: 23.14
        },
        {
            id: '21',
            source: require('../assets/Image21.png'), 
            thumbnail: require('../assets/Image21Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 65.569,
            iconFromTop: 427.04,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '22',
            source: require('../assets/Image22.png'), 
            thumbnail: require('../assets/Image22Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 777.653,
            iconFromTop: 1847.163,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '23',
            source: require('../assets/Image23.png'), 
            thumbnail: require('../assets/Image23Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 90.45,
            iconFromTop: 694.186,
            iconWidth: 17,
            iconHeight: 24.586
        },
        {
            id: '24',
            source: require('../assets/Image24.png'), 
            thumbnail: require('../assets/Image24Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1448.435,
            iconFromTop: 2564.035,
            iconWidth: 20,
            iconHeight: 28.924 
        },
        {
            id: '25',
            source: require('../assets/Image25.png'), 
            thumbnail: require('../assets/Image25Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 114.673,
            iconFromTop: 600.186,
            iconWidth: 20,
            iconHeight: 28.924 
        },
        {
            id: '26',
            source: require('../assets/Image26.png'), 
            thumbnail: require('../assets/Image26Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1371.576,
            iconFromTop: 1994.685,
            iconWidth: 20,
            iconHeight: 28.924
        },
        {
            id: '27',
            source: require('../assets/Image27.png'), 
            thumbnail: require('../assets/Image27Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 537.469,
            iconFromTop: 2175.534,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '28',
            source: require('../assets/Image28.png'), 
            thumbnail: require('../assets/Image28Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1440.374,
            iconFromTop: 2267.539,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '29',
            source: require('../assets/Image29.png'), 
            thumbnail: require('../assets/Image29Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 154.05,
            iconFromTop: 2288.793,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '30',
            source: require('../assets/Image30.png'), 
            thumbnail: require('../assets/Image30Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 749.479,
            iconFromTop: 1394.943,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '31',
            source: require('../assets/Image31.png'), 
            thumbnail: require('../assets/Image31Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 468.428,
            iconFromTop: 1343.271,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '32',
            source: require('../assets/Image32.png'), 
            thumbnail: require('../assets/Image32Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 1431.192,
            iconFromTop: 1874.432,
            iconWidth: 18,
            iconHeight: 26.032
        },
        {
            id: '33',
            source: require('../assets/Image33.png'), 
            thumbnail: require('../assets/Image33Thumbnail.png'),
            width: 1500,
            height: 2708,
            iconFromLeft: 843.762,
            iconFromTop: 1726.056,
            iconWidth: 18,
            iconHeight: 26.032
        }
    ]
}
